
include:
  - board: nice_nano_v2
    shield: test
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y
    artificial-name: test
  - board: nice_nano_v2
    shield: settings_reset
    artificial-name: settings_reset-akdk_bt1-zmk
